modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/VkProfi/packet_size_doubler/issues"
license = "${mod_license}"

[[mods]] 
modId = "${mod_id}"
version = "${mod_version}" 
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''
credits="Made for InCube"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"